%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'model6a';
M_.dynare_version = '4.6.0';
oo_.dynare_version = '4.6.0';
options_.dynare_version = '4.6.0';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('model6a.log');
M_.exo_names = cell(9,1);
M_.exo_names_tex = cell(9,1);
M_.exo_names_long = cell(9,1);
M_.exo_names(1) = {'sA'};
M_.exo_names_tex(1) = {'sA'};
M_.exo_names_long(1) = {'sA'};
M_.exo_names(2) = {'sG'};
M_.exo_names_tex(2) = {'sG'};
M_.exo_names_long(2) = {'sG'};
M_.exo_names(3) = {'si'};
M_.exo_names_tex(3) = {'si'};
M_.exo_names_long(3) = {'si'};
M_.exo_names(4) = {'sunspot'};
M_.exo_names_tex(4) = {'sunspot'};
M_.exo_names_long(4) = {'sunspot'};
M_.exo_names(5) = {'sunspot2'};
M_.exo_names_tex(5) = {'sunspot2'};
M_.exo_names_long(5) = {'sunspot2'};
M_.exo_names(6) = {'sunspot3'};
M_.exo_names_tex(6) = {'sunspot3'};
M_.exo_names_long(6) = {'sunspot3'};
M_.exo_names(7) = {'sunspot4'};
M_.exo_names_tex(7) = {'sunspot4'};
M_.exo_names_long(7) = {'sunspot4'};
M_.exo_names(8) = {'sunspot5'};
M_.exo_names_tex(8) = {'sunspot5'};
M_.exo_names_long(8) = {'sunspot5'};
M_.exo_names(9) = {'sunspot6'};
M_.exo_names_tex(9) = {'sunspot6'};
M_.exo_names_long(9) = {'sunspot6'};
M_.endo_names = cell(34,1);
M_.endo_names_tex = cell(34,1);
M_.endo_names_long = cell(34,1);
M_.endo_names(1) = {'C'};
M_.endo_names_tex(1) = {'C'};
M_.endo_names_long(1) = {'C'};
M_.endo_names(2) = {'H'};
M_.endo_names_tex(2) = {'H'};
M_.endo_names_long(2) = {'H'};
M_.endo_names(3) = {'lambda'};
M_.endo_names_tex(3) = {'lambda'};
M_.endo_names_long(3) = {'lambda'};
M_.endo_names(4) = {'P'};
M_.endo_names_tex(4) = {'P'};
M_.endo_names_long(4) = {'P'};
M_.endo_names(5) = {'W'};
M_.endo_names_tex(5) = {'W'};
M_.endo_names_long(5) = {'W'};
M_.endo_names(6) = {'B'};
M_.endo_names_tex(6) = {'B'};
M_.endo_names_long(6) = {'B'};
M_.endo_names(7) = {'y'};
M_.endo_names_tex(7) = {'y'};
M_.endo_names_long(7) = {'y'};
M_.endo_names(8) = {'Y'};
M_.endo_names_tex(8) = {'Y'};
M_.endo_names_long(8) = {'Y'};
M_.endo_names(9) = {'PI'};
M_.endo_names_tex(9) = {'PI'};
M_.endo_names_long(9) = {'PI'};
M_.endo_names(10) = {'pD'};
M_.endo_names_tex(10) = {'pD'};
M_.endo_names_long(10) = {'pD'};
M_.endo_names(11) = {'MC'};
M_.endo_names_tex(11) = {'MC'};
M_.endo_names_long(11) = {'MC'};
M_.endo_names(12) = {'theta'};
M_.endo_names_tex(12) = {'theta'};
M_.endo_names_long(12) = {'theta'};
M_.endo_names(13) = {'mu'};
M_.endo_names_tex(13) = {'mu'};
M_.endo_names_long(13) = {'mu'};
M_.endo_names(14) = {'e'};
M_.endo_names_tex(14) = {'e'};
M_.endo_names_long(14) = {'e'};
M_.endo_names(15) = {'CD'};
M_.endo_names_tex(15) = {'CD'};
M_.endo_names_long(15) = {'CD'};
M_.endo_names(16) = {'CF'};
M_.endo_names_tex(16) = {'CF'};
M_.endo_names_long(16) = {'CF'};
M_.endo_names(17) = {'PD'};
M_.endo_names_tex(17) = {'PD'};
M_.endo_names_long(17) = {'PD'};
M_.endo_names(18) = {'PF'};
M_.endo_names_tex(18) = {'PF'};
M_.endo_names_long(18) = {'PF'};
M_.endo_names(19) = {'GD'};
M_.endo_names_tex(19) = {'GD'};
M_.endo_names_long(19) = {'GD'};
M_.endo_names(20) = {'GF'};
M_.endo_names_tex(20) = {'GF'};
M_.endo_names_long(20) = {'GF'};
M_.endo_names(21) = {'G'};
M_.endo_names_tex(21) = {'G'};
M_.endo_names_long(21) = {'G'};
M_.endo_names(22) = {'T'};
M_.endo_names_tex(22) = {'T'};
M_.endo_names_long(22) = {'T'};
M_.endo_names(23) = {'A'};
M_.endo_names_tex(23) = {'A'};
M_.endo_names_long(23) = {'A'};
M_.endo_names(24) = {'i'};
M_.endo_names_tex(24) = {'i'};
M_.endo_names_long(24) = {'i'};
M_.endo_names(25) = {'X'};
M_.endo_names_tex(25) = {'X'};
M_.endo_names_long(25) = {'X'};
M_.endo_names(26) = {'AC'};
M_.endo_names_tex(26) = {'AC'};
M_.endo_names_long(26) = {'AC'};
M_.endo_names(27) = {'ACD'};
M_.endo_names_tex(27) = {'ACD'};
M_.endo_names_long(27) = {'ACD'};
M_.endo_names(28) = {'ACF'};
M_.endo_names_tex(28) = {'ACF'};
M_.endo_names_long(28) = {'ACF'};
M_.endo_names(29) = {'lambdaS'};
M_.endo_names_tex(29) = {'lambdaS'};
M_.endo_names_long(29) = {'lambdaS'};
M_.endo_names(30) = {'thetaS'};
M_.endo_names_tex(30) = {'thetaS'};
M_.endo_names_long(30) = {'thetaS'};
M_.endo_names(31) = {'yS'};
M_.endo_names_tex(31) = {'yS'};
M_.endo_names_long(31) = {'yS'};
M_.endo_names(32) = {'pDS'};
M_.endo_names_tex(32) = {'pDS'};
M_.endo_names_long(32) = {'pDS'};
M_.endo_names(33) = {'YS'};
M_.endo_names_tex(33) = {'YS'};
M_.endo_names_long(33) = {'YS'};
M_.endo_names(34) = {'PS'};
M_.endo_names_tex(34) = {'PS'};
M_.endo_names_long(34) = {'PS'};
M_.endo_partitions = struct();
M_.param_names = cell(16,1);
M_.param_names_tex = cell(16,1);
M_.param_names_long = cell(16,1);
M_.param_names(1) = {'psi'};
M_.param_names_tex(1) = {'psi'};
M_.param_names_long(1) = {'psi'};
M_.param_names(2) = {'sigma'};
M_.param_names_tex(2) = {'sigma'};
M_.param_names_long(2) = {'sigma'};
M_.param_names(3) = {'alpha'};
M_.param_names_tex(3) = {'alpha'};
M_.param_names_long(3) = {'alpha'};
M_.param_names(4) = {'phi'};
M_.param_names_tex(4) = {'phi'};
M_.param_names_long(4) = {'phi'};
M_.param_names(5) = {'eta'};
M_.param_names_tex(5) = {'eta'};
M_.param_names_long(5) = {'eta'};
M_.param_names(6) = {'gamma'};
M_.param_names_tex(6) = {'gamma'};
M_.param_names_long(6) = {'gamma'};
M_.param_names(7) = {'omega'};
M_.param_names_tex(7) = {'omega'};
M_.param_names_long(7) = {'omega'};
M_.param_names(8) = {'rho'};
M_.param_names_tex(8) = {'rho'};
M_.param_names_long(8) = {'rho'};
M_.param_names(9) = {'zetaA'};
M_.param_names_tex(9) = {'zetaA'};
M_.param_names_long(9) = {'zetaA'};
M_.param_names(10) = {'zetaG'};
M_.param_names_tex(10) = {'zetaG'};
M_.param_names_long(10) = {'zetaG'};
M_.param_names(11) = {'zetai'};
M_.param_names_tex(11) = {'zetai'};
M_.param_names_long(11) = {'zetai'};
M_.param_names(12) = {'zetaX'};
M_.param_names_tex(12) = {'zetaX'};
M_.param_names_long(12) = {'zetaX'};
M_.param_names(13) = {'kappa'};
M_.param_names_tex(13) = {'kappa'};
M_.param_names_long(13) = {'kappa'};
M_.param_names(14) = {'n'};
M_.param_names_tex(14) = {'n'};
M_.param_names_long(14) = {'n'};
M_.param_names(15) = {'s'};
M_.param_names_tex(15) = {'s'};
M_.param_names_long(15) = {'s'};
M_.param_names(16) = {'varphi'};
M_.param_names_tex(16) = {'varphi'};
M_.param_names_long(16) = {'varphi'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 9;
M_.endo_nbr = 34;
M_.param_nbr = 16;
M_.orig_endo_nbr = 34;
M_.aux_vars = [];
M_.Sigma_e = zeros(9, 9);
M_.Correlation_matrix = eye(9, 9);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.orig_eq_nbr = 34;
M_.eq_nbr = 34;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 0;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 0;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 13;
 0 14;
 0 15;
 0 16;
 0 17;
 1 18;
 0 19;
 0 20;
 0 21;
 2 22;
 0 23;
 0 24;
 0 25;
 3 26;
 0 27;
 0 28;
 0 29;
 0 30;
 0 31;
 0 32;
 4 33;
 0 34;
 5 35;
 6 36;
 0 37;
 0 38;
 0 39;
 0 40;
 7 41;
 8 42;
 9 43;
 10 44;
 11 45;
 12 46;]';
M_.nstatic = 22;
M_.nfwrd   = 0;
M_.npred   = 12;
M_.nboth   = 0;
M_.nsfwrd   = 0;
M_.nspred   = 12;
M_.ndynamic   = 12;
M_.dynamic_tmp_nbr = [25; 11; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'FOC for consumption' ;
  2 , 'name' , 'FOC for labour (hours)' ;
  3 , 'name' , 'Euler equation' ;
  4 , 'name' , 'S: lambda forecasting error' ;
  5 , 'name' , 'Budget constraint' ;
  6 , 'name' , 'Aggregate consumption' ;
  7 , 'name' , 'Household s demand for domestic goods' ;
  8 , 'name' , 'Household s demand for imported goods' ;
  9 , 'name' , 'Price index' ;
  10 , 'name' , 'Balanced budget (Ricardian equivalence)' ;
  11 , 'name' , 'Exogenous process of government spending' ;
  12 , 'name' , 'Goverment expenditure' ;
  13 , 'name' , 'Government s demand for domestic goods' ;
  14 , 'name' , 'Government s demand for domestic goods' ;
  15 , 'name' , 'Exogenous process of the nominal interest rates' ;
  16 , 'name' , 'Adjustment costs' ;
  17 , 'name' , 'Share of adjustment costs purchased via domestic goods' ;
  18 , 'name' , 'Share of adjustment costs purchased via imported goods' ;
  19 , 'name' , 'Pricing equation' ;
  20 , 'name' , 'Theta equation' ;
  21 , 'name' , 'S: pD forecasting error' ;
  22 , 'name' , 'S: theta forecasting error' ;
  23 , 'name' , 'S: y forecasting error' ;
  24 , 'name' , 'S: Y forecasting error' ;
  25 , 'name' , 'S: P forecasting error' ;
  26 , 'name' , 'Marginal cost' ;
  27 , 'name' , 'Individual markup' ;
  28 , 'name' , 'Law of motion for the demand shifter' ;
  29 , 'name' , 'Exogenous process of productivity' ;
  30 , 'name' , 'Aggregate domestic price level' ;
  31 , 'name' , 'Aggregate output' ;
  32 , 'name' , 'Aggregate resources' ;
  33 , 'name' , 'Aggregate profits' ;
  34 , 'name' , 'Individual output' ;
};
M_.mapping.C.eqidx = [1 2 5 6 7 8 32 ];
M_.mapping.H.eqidx = [1 2 5 31 33 ];
M_.mapping.lambda.eqidx = [1 2 3 ];
M_.mapping.P.eqidx = [1 5 7 8 9 10 13 14 16 17 18 19 32 33 ];
M_.mapping.W.eqidx = [2 5 26 33 ];
M_.mapping.B.eqidx = [5 15 ];
M_.mapping.y.eqidx = [19 26 28 34 ];
M_.mapping.Y.eqidx = [16 19 31 32 33 34 ];
M_.mapping.PI.eqidx = [5 33 ];
M_.mapping.pD.eqidx = [16 19 20 27 30 32 ];
M_.mapping.MC.eqidx = [19 26 27 ];
M_.mapping.theta.eqidx = [19 20 ];
M_.mapping.mu.eqidx = [27 ];
M_.mapping.e.eqidx = [20 28 30 31 34 ];
M_.mapping.CD.eqidx = [6 7 ];
M_.mapping.CF.eqidx = [6 8 32 ];
M_.mapping.PD.eqidx = [7 9 13 17 30 ];
M_.mapping.PF.eqidx = [8 9 14 18 32 ];
M_.mapping.GD.eqidx = [12 13 ];
M_.mapping.GF.eqidx = [12 14 32 ];
M_.mapping.G.eqidx = [10 11 12 13 14 32 ];
M_.mapping.T.eqidx = [5 10 ];
M_.mapping.A.eqidx = [26 29 31 ];
M_.mapping.i.eqidx = [3 5 15 ];
M_.mapping.X.eqidx = [32 ];
M_.mapping.AC.eqidx = [16 17 18 ];
M_.mapping.ACD.eqidx = [17 ];
M_.mapping.ACF.eqidx = [18 32 ];
M_.mapping.lambdaS.eqidx = [3 4 ];
M_.mapping.thetaS.eqidx = [20 22 ];
M_.mapping.yS.eqidx = [20 23 ];
M_.mapping.pDS.eqidx = [20 21 ];
M_.mapping.YS.eqidx = [20 24 ];
M_.mapping.PS.eqidx = [20 25 ];
M_.mapping.sA.eqidx = [29 ];
M_.mapping.sG.eqidx = [11 ];
M_.mapping.si.eqidx = [15 ];
M_.mapping.sunspot.eqidx = [4 ];
M_.mapping.sunspot2.eqidx = [21 ];
M_.mapping.sunspot3.eqidx = [22 ];
M_.mapping.sunspot4.eqidx = [23 ];
M_.mapping.sunspot5.eqidx = [24 ];
M_.mapping.sunspot6.eqidx = [25 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [6 10 14 21 23 24 29 30 31 32 33 34 ];
M_.exo_names_orig_ord = [1:9];
M_.maximum_lag = 1;
M_.maximum_lead = 0;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 0;
oo_.steady_state = zeros(34, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(9, 1);
M_.params = NaN(16, 1);
M_.endo_trends = struct('deflator', cell(34, 1), 'log_deflator', cell(34, 1), 'growth_factor', cell(34, 1), 'log_growth_factor', cell(34, 1));
M_.NNZDerivatives = [139; -1; -1; ];
M_.static_tmp_nbr = [21; 11; 0; 0; ];
close all;
M_.params(8) = 0.02177818086464089;
rho = M_.params(8);
M_.params(6) = 2;
gamma = M_.params(6);
M_.params(7) = 1.455;
omega = M_.params(7);
M_.params(14) = 0.5;
n = M_.params(14);
M_.params(15) = 2.9;
s = M_.params(15);
M_.params(13) = 0.00742;
kappa = M_.params(13);
M_.params(10) = 0.9;
zetaG = M_.params(10);
M_.params(11) = 0.9;
zetai = M_.params(11);
M_.params(12) = 0.9;
zetaX = M_.params(12);
M_.params(2) = M_.params(15);
sigma = M_.params(2);
M_.params(4) = 0.75;
phi = M_.params(4);
M_.params(5) = 0.125;
eta = M_.params(5);
M_.params(9) = 0.9;
zetaA = M_.params(9);
M_.params(1) = .3183969939;
psi = M_.params(1);
M_.params(3) = 0.3333333333333333;
alpha = M_.params(3);
M_.params(16) = 0.1;
varphi = M_.params(16);
steady;
model_diagnostics(M_,options_,oo_);
shockA = oo_.steady_state(23) * 0.01;
shockG = oo_.steady_state(21) * 0.03;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = shockA;
M_.Sigma_e(2, 2) = shockG;
options_.ar = 1;
options_.irf = 20;
options_.order = 1;
var_list_ = {'PD';'MC';'mu';'W';'CD';'CF';'H';'GD';'GF';'C';'i';'e';'Y'};
[info, oo_, options_] = stoch_simul(M_, options_, oo_, var_list_);
save('model6a_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('model6a_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('model6a_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('model6a_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('model6a_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('model6a_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('model6a_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 2 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
