%What if? The role of market power in the Portuguese twin recessions
%This is a simple homogenous-agent (semi-small) open-economy model 
%with an endogenous markup generated by dynamic demand à la Santos et al. (2021)
% Luís Costa & João Costa Filho developed it to submit to the PEJ conference 2021. 
%We can complicate it later.
%Assumptions: discrete time, infinitely-living agents, stocks measured at the begining of the period, etc.
%Correspondence: João Ricardo Costa Filho; joao.costa@fgv.br


//////////////////////////////////////////////////////////////////////////////////////////////////
//This is a free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.  See <http://www.gnu.org/licenses/> for more information.
//////////////////////////////////////////////////////////////////////////////////////////////////

% We follow Farmer, Khramov Nicolò JECD 2015 paper, "Solving and estimating indeterminate DSGE models"


close all;

%--------------------------------------------------------------------------------------------------------------------------------------
% 0. Data for the quantitaive exercises
%--------------------------------------------------------------------------------------------------------------------------------------

%dgov   = xlsread('data','Sheet1',['B','2',':','B','101']);   %observed Log-detrended government spending 
dgov   = xlsread('data','Sheet1',['B','2',':','B','26']);   %observed Log-detrended government spending 

%--------------------------------------------------------------------------------------------------------------------------------------
% 1. Defining variables
%--------------------------------------------------------------------------------------------------------------------------------------

%Endogenous variables
var C, H, P, lambda, W, B, PI, T, G, p, MC, theta, y, e, A, mu, Y, X, i, lambdas, thetas, ys;

% C      :  aggregate real consumption
% H      :  aggregate hours of work
% P      :  aggregate price index,
% lambda :  households' Hamiltonian multiplier
% W      :  wage rate
% B      :  stock of net assets
% PI     :  aggregate profits
% T      :  lump-sum tax
% G      :  aggregate real government consumption
% p      :  individual price
% MC     :  individual marginal cost,
% theta  :  firms' Hamiltonian multiplier
% y      :  individual output
% e      :  demand shifter
% A      :  productivity
% mu     :  individual markup
% Y      :  aggregate real output, as value added
% X      :  aggregate real net exports
% i      :  nominal interest rate

%Exogenous variables
varexo sA sG, sX, si, sunspot, sunspot2, sunspot3; % sX; 

% sA : productivity shock
% sG : government spending shock
% si : interest rate shock
% sX : net exports shock

parameters 
psi sigma alpha phi eta gamma omega rho zetaA zetaG zetai kappa;

%--------------------------------------------------------------------------------------------------------------------------------------
% 2. Calibration
%--------------------------------------------------------------------------------------------------------------------------------------
sigma = 2.9;                              % price-elasticity of demand 
alpha = 1/3;                              % 1 - alpha: share of labor in the production
phi   = 0.75;                             % future demand sensitivity to current sales
%eta   = 0.5;                              % demand ``loss"
eta = 0.5 / 4;
rho   = ( ( 1 + 0.09 )^( 1 / 4 ) ) - 1 ;  % discount rate 
%rho = 0.09;
gamma = 2;                                % elasticity of intertemporal substitution
omega = 1.455;                            % exponent of labor in utility function 
zetaA = 0.9;                              % technology process autoregressive weight
zetaG = 0.9;                              % government spending process autoregressive weight
zetai = 0.9;
kappa = 0.07;
%psi   = 1.470967536;                      % demand
psi = .3264644442;

%--------------------------------------------------------------------------------------------------------------------------------------
% 3. Model 
%--------------------------------------------------------------------------------------------------------------------------------------

model; 

%%%%% Household block
% eq. () - FOC for consumption
( C - ( H ^ omega ) / omega ) ^ ( - gamma ) = lambda * P;

%eq. () - FOC for labour (hours)
H ^ ( omega - 1 ) * (  ( C - ( H ^ omega ) / omega ) ^ ( - gamma ) ) = W * lambda;

%eq. () - Euler equation
%lambda(+1) * ( 1 +  i ) = ( 1 + rho )  * lambda;

lambdas * ( 1 +  i ) = ( 1 + rho )  * lambda;

lambdas - lambdas(-1) = sunspot;

% eq. () - Budget constraint 
B = ( 1 + i(-1) ) * B(-1) + W * H + PI - T - P * C;

%%%%% Government block
% eq. () - Balanced budget (Ricardian equivalence)
P * G = T;

% eq. () - Exogenous process of government spending
log( G ) = ( 1 - zetaG) * log( STEADY_STATE(G) ) + zetaG * log ( G(-1) ) + sG;

%%%%% Rest of the world block

% eq. () - Exogenous process of net exports
%log( X ) = ( 1 - zetaX) * 0 + zetaX * log ( X(-1) ) + sX;
X = 0 + sX;
 
% eq. () - Exogenous process of nominal interest rates 
i = rho + si;


%%%%% Firms block

%eq. () - pricing equation
( ( sigma - 1 ) / sigma ) * p - MC + phi * theta = 0;

% eq () - 
%1 / sigma * ( p(+1) * y(+1) / e ) - ( 1 - eta ) * theta(+1) = ( 1 + rho ) * theta;
1 / sigma * ( p(+1) * ys / e ) - ( 1 - eta ) * thetas = ( 1 + rho ) * thetas(-1);

thetas - thetas(-1) = sunspot2;
ys - ys(-1) = sunspot3;

%eq. () - Marginal cost
MC = ( W / ( ( 1 - alpha ) * A ^ ( 1 / ( 1 - alpha ) ) ) ) * y ^ ( alpha / ( 1 - alpha ) )  ;

%eq. () - Individual markup
mu = p / MC;

%eq. () - Law of motion for the demand shifter
e = phi * y + ( 1 - eta ) * e(-1);

%eq. () - Exogenous process of productivity
log( A ) = ( 1 - zetaA) * log( STEADY_STATE(A) ) + zetaA * log ( A(-1) ) + sA;

%%%%% Aggregation block

%eq. ()
P = ( psi * e(-1) ) ^( -1 / ( sigma - 1 ) ) * p;

%eq. ()
Y = ( psi * e(-1) ) ^( 1 / ( sigma - 1 ) ) * A * H ^ ( 1 - alpha );

%eq. ()
Y = C + G + X;

%eq. ()
PI = P * Y - W * H;

%eq. ()
y = ( ( psi * e(-1) ) ^( - 1 / ( sigma - 1 ) ) ) * Y;

end;
%--------------------------------------------------------------------------------------------------------------------------------------

%--------------------------------------------------------------------------------------------------------------------------------------
% 4. Steady State
%--------------------------------------------------------------------------------------------------------------------------------------

steady_state_model;
%initval;

X      = 0;
B      = 0;
i      = rho;
e      = 1 / psi;
P      = 1;
p      = P;
%theta  = .1445817972;
theta = .3029941241e-1;
thetas = theta;
%MC     = .7636087617; 
MC = .6778969731;
%mu     = 1.309571144;
mu = 1.475150413;
%A      = .8874291610;
A = .9996337344;
%Y      = .4532164376;
Y = .5105201184;
y      = Y;
ys = y;
%G      = .1528423488;
G = .1721673963;
T      = G * P;
%C      = .3003740888;
C = .3383527221;
%W      = .6321605073;
W = .6321605070;
%PI     = .2224964090;
PI = .2798000899;
%lambda = 49.73078902;
lambda = 30.93900550;
lambdas = lambda;
H      = 1865 /( 365 * 14 );

end;

steady;
%resid;

%--------------------------------------------------------------------------------------------------------------------------------------
% 5. Simulation
%--------------------------------------------------------------------------------------------------------------------------------------

shockA = oo_.steady_state(15) * 0.01;
shockG = oo_.steady_state(8) * 0.03;

shocks;
var sG = shockG;
var sA = shockA;
%periods 1:25;
%values (dgov);
end;

stoch_simul(ar=1, order=1,irf=10)  y P MC mu W C H A;

 


%--------------------------------------------------------------------------------------------------------------------------------------
% 6. Bayesian estimation 
%--------------------------------------------------------------------------------------------------------------------------------------

 
%TBD