%What if? The role of market power in the Portuguese twin recessions
%This is a simple homogenous-agent (semi-small) open-economy model 
%with an endogenous markup generated by dynamic demand à la Santos et al. (2021)
% Luís Costa & João Costa Filho developed it to submit to the PEJ conference 2021. 
%We can complicate it later.
%Assumptions: discrete time, infinitely-living agents, stocks measured at the begining of the period, etc.
%Correspondence: João Ricardo Costa Filho; joao.costa@fgv.br

close all;

%--------------------------------------------------------------------------------------------------------------------------------------
% 1. Data
%--------------------------------------------------------------------------------------------------------------------------------------

dgov   = xlsread('data','Sheet1',['B','2',':','B','101']);   %observed Log-detrended government spending 

%--------------------------------------------------------------------------------------------------------------------------------------
% 1. Defining variables
%--------------------------------------------------------------------------------------------------------------------------------------

%Endogenous variables
var C, H, P, lambda, W, B, PI, T, G, p, MC, theta, y, e, A, mu, Y, X, i;

% C :       aggregate real consumption
% H :       aggregate hours of work
% P :       aggregate price index,
% lambda :  households' Hamilton multiplier
% W :       wage rate
% B :       stock of net assets
% PI :      aggregate profits
% T :       lump-sum tax
% G :       aggregate real government consumption
% p :       individual price
% MC :      individual marginal cost,
% theta :   firms' Hamiltion multiplier
% y :       individual output
% e :       demand shifter
% A :       productivity
% mu :      individual markup
% Y :       aggregate real output, as value added
% X :       aggregate real net exports
% i :       nominal interest rate

%Exogenous variables
varexo sA sG, sX, si; % sunspot; % sX; 

% sA :
% sG :
% si :
% sX :

parameters 
psi sigma alpha phi eta gamma omega rho zetaA zetaG gs kappa;

%--------------------------------------------------------------------------------------------------------------------------------------
% 2. Calibration
%--------------------------------------------------------------------------------------------------------------------------------------
sigma = 2.9;
alpha = 1/3;         %share of domestic capital in the production
phi   = 0.75; 
eta   = 0.5;  
rho   = ( ( 1 + 0.09 )^( 1 / 4 ) ) - 1 ;  % discount rate 
gamma = 2;                                %intertemporal elasticity of substitution
omega = 1.455;                            %exponent of labor in utility function 
zetaA  = 0.9;
zetaG  = 0.8;
hbar  = 1865 / ( 365 * 24 );
gs   = 0.341;
%mubar = 1.4;
psi = 3.24302403313243;
kappa=0.00774;

%--------------------------------------------------------------------------------------------------------------------------------------
% 3. Model 
%--------------------------------------------------------------------------------------------------------------------------------------

model; 

#Ybar = 0.205569449950309;
#Gbar = 0.0700991824330554;
#ibar = rho;
#Abar = 0.576556784777983;
#Xbar = 0;

%%%%% Household block
% eq. () - FOC for consumption
( C - ( H ^ omega ) / omega ) ^ ( - gamma ) = lambda * P;

%eq. () - FOC for labour (hours)
H ^ ( omega - 1 ) * (  ( C - ( H ^ omega ) / omega ) ^ ( - gamma ) ) = W * lambda;

%eq. () - Euler equation
lambda(+1) * ( 1 +  i ) = ( 1 + rho )  * lambda;

%ls * ( 1 +  i ) = ( 1 + rho )  * lambda;

%lambda - ls(-1) = sunspot;

% eq. () - Budget constraint 
B = ( 1 + i(-1) ) * B(-1) + W * H + PI - T - P * C;

%%%%% Government block
% eq. () - Balanced budget (Ricardian equivalence)
P * G = T;

% eq. () - Exogenous process of government spending
log( G ) = ( 1 - zetaG) * log( Gbar ) + zetaG * log ( G(-1) ) + sG;

%%%%% Rest of the world block

% eq. () - Exogenous process of net exports
%log( X ) = ( 1 - zetaX) * 0 + zetaX * log ( X(-1) ) + sX;
X = 0 + sX;
 
% eq. () - Exogenous process of nominal interest rates 
%i = rho + kappa * ( exp ( -B ) - 1 ) + si;
i = rho + si;

%%%%% Firms block

%eq. () - pricing equation
( ( sigma - 1 ) / sigma ) * p - MC + phi * theta = 0;

% eq () - 
1 / sigma * ( p(+1) * y(+1) / e ) - ( 1 - eta ) * theta(+1) = ( 1 + rho ) * theta;

%eq. () - Marginal cost
MC = ( W / ( ( 1 - alpha ) * A ^ ( 1 / ( 1 - alpha ) ) ) ) * y ^ ( alpha / ( 1 - alpha ) )  ;

%eq. () - Individual markup
mu = p / MC;

%eq. () - Law of motion for the demand shifter
e = phi * y + ( 1 - eta ) * e(-1);

%eq. () - Exogenous process of productivity
log( A ) = ( 1 - zetaA) * log( Abar ) + zetaA * log ( A(-1) ) + sA;

%%%%% Aggregation block

%eq. ()
P = ( psi * e(-1) ) ^( -1 / ( sigma - 1 ) ) * p;

%eq. ()
Y = ( psi * e(-1) ) ^( 1 / ( sigma - 1 ) ) * A * H ^ ( 1 - alpha );

%eq. ()
Y = C + G + X;

%eq. ()
PI = P * Y - W * H;

%eq. ()
y = ( ( psi * e(-1) ) ^( 1 / ( sigma - 1 ) ) ) * Y;

end;
%--------------------------------------------------------------------------------------------------------------------------------------

%--------------------------------------------------------------------------------------------------------------------------------------
% 4. Steady State
%--------------------------------------------------------------------------------------------------------------------------------------

%steady_state_model;
initval;

X = 0;
B = 0;
i = rho;
e = 1 / psi;
Y = .205569449950309;
y = Y;
theta = 0.151063446934592; 
p = 1;
P = p;
MC = 0.768469998994047;
mu = 1.30128697451954;
G = 0.0700991824330554;
T = G * P;
C = 0.135470267517254;
A = 0.576556784777983;
H = 0.2129;
W = 0.494674475699557;
PI = 0.100253479952630;
lambda = 251.248982342607;

end;

%steady;
%resid;

%--------------------------------------------------------------------------------------------------------------------------------------
% 5. Impulse-response functions
%--------------------------------------------------------------------------------------------------------------------------------------

shocks;

var sG;
periods 1:100;
values (dgov);
end;

%plot( ( log( oo_.endo_simul(16,1:18) ) - log( oo_.steady_state(16) ) ) * 100 ,'b--');
%title('Markup')

steady;

%stoch_simul(hp_filter = 1600, order = 1, irf = 20);

perfect_foresight_setup(periods=100);

perfect_foresight_solver;

rplot mu;

t = [2010.50:0.25:2013.75]';
plot( t, ( log( oo_.endo_simul(16,1:14) ) - log( oo_.steady_state(16) ) ) * 100 ,'k');
title('Markup')





