%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_Course';
M_.dynare_version = '4.6.0';
oo_.dynare_version = '4.6.0';
options_.dynare_version = '4.6.0';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_Course.log');
M_.exo_names = cell(3,1);
M_.exo_names_tex = cell(3,1);
M_.exo_names_long = cell(3,1);
M_.exo_names(1) = {'epsA'};
M_.exo_names_tex(1) = {'\varepsilon^{A}'};
M_.exo_names_long(1) = {'epsA'};
M_.exo_names(2) = {'epsG'};
M_.exo_names_tex(2) = {'\varepsilon^G'};
M_.exo_names_long(2) = {'epsG'};
M_.exo_names(3) = {'epsM'};
M_.exo_names_tex(3) = {'\varepsilon^M'};
M_.exo_names_long(3) = {'epsM'};
M_.endo_names = cell(35,1);
M_.endo_names_tex = cell(35,1);
M_.endo_names_long = cell(35,1);
M_.endo_names(1) = {'LAMBDA'};
M_.endo_names_tex(1) = {'\Lambda'};
M_.endo_names_long(1) = {'LAMBDA'};
M_.endo_names(2) = {'LAMBDAC'};
M_.endo_names_tex(2) = {'\Lambda^C'};
M_.endo_names_long(2) = {'LAMBDAC'};
M_.endo_names(3) = {'Rex'};
M_.endo_names_tex(3) = {'R^{ex}'};
M_.endo_names_long(3) = {'Rex'};
M_.endo_names(4) = {'h'};
M_.endo_names_tex(4) = {'h'};
M_.endo_names_long(4) = {'h'};
M_.endo_names(5) = {'WP'};
M_.endo_names_tex(5) = {'WP'};
M_.endo_names_long(5) = {'WP'};
M_.endo_names(6) = {'YW'};
M_.endo_names_tex(6) = {'Y^W'};
M_.endo_names_long(6) = {'YW'};
M_.endo_names(7) = {'Y'};
M_.endo_names_tex(7) = {'Y'};
M_.endo_names_long(7) = {'Y'};
M_.endo_names(8) = {'PWP'};
M_.endo_names_tex(8) = {'\frac{P^W}{P}'};
M_.endo_names_long(8) = {'PWP'};
M_.endo_names(9) = {'K'};
M_.endo_names_tex(9) = {'K'};
M_.endo_names_long(9) = {'K'};
M_.endo_names(10) = {'I'};
M_.endo_names_tex(10) = {'I'};
M_.endo_names_long(10) = {'I'};
M_.endo_names(11) = {'tax'};
M_.endo_names_tex(11) = {'tax'};
M_.endo_names_long(11) = {'tax'};
M_.endo_names(12) = {'C'};
M_.endo_names_tex(12) = {'C'};
M_.endo_names_long(12) = {'C'};
M_.endo_names(13) = {'A'};
M_.endo_names_tex(13) = {'A'};
M_.endo_names_long(13) = {'A'};
M_.endo_names(14) = {'G'};
M_.endo_names_tex(14) = {'G'};
M_.endo_names_long(14) = {'G'};
M_.endo_names(15) = {'X'};
M_.endo_names_tex(15) = {'X'};
M_.endo_names_long(15) = {'X'};
M_.endo_names(16) = {'Q'};
M_.endo_names_tex(16) = {'Q'};
M_.endo_names_long(16) = {'Q'};
M_.endo_names(17) = {'XX'};
M_.endo_names_tex(17) = {'XX'};
M_.endo_names_long(17) = {'XX'};
M_.endo_names(18) = {'Z1'};
M_.endo_names_tex(18) = {'Z^1'};
M_.endo_names_long(18) = {'Z1'};
M_.endo_names(19) = {'Z2'};
M_.endo_names_tex(19) = {'Z^2'};
M_.endo_names_long(19) = {'Z2'};
M_.endo_names(20) = {'MC'};
M_.endo_names_tex(20) = {'MC'};
M_.endo_names_long(20) = {'MC'};
M_.endo_names(21) = {'H'};
M_.endo_names_tex(21) = {'H'};
M_.endo_names_long(21) = {'H'};
M_.endo_names(22) = {'Htilde'};
M_.endo_names_tex(22) = {'\tilde{H}'};
M_.endo_names_long(22) = {'Htilde'};
M_.endo_names(23) = {'J'};
M_.endo_names_tex(23) = {'J'};
M_.endo_names_long(23) = {'J'};
M_.endo_names(24) = {'Jtilde'};
M_.endo_names_tex(24) = {'\tilde{J}'};
M_.endo_names_long(24) = {'Jtilde'};
M_.endo_names(25) = {'PIE'};
M_.endo_names_tex(25) = {'\Pi'};
M_.endo_names_long(25) = {'PIE'};
M_.endo_names(26) = {'Rn'};
M_.endo_names_tex(26) = {'Rn'};
M_.endo_names_long(26) = {'Rn'};
M_.endo_names(27) = {'INVPIE'};
M_.endo_names_tex(27) = {'\frac{1}{\Pi}'};
M_.endo_names_long(27) = {'INVPIE'};
M_.endo_names(28) = {'RR'};
M_.endo_names_tex(28) = {'RR'};
M_.endo_names_long(28) = {'RR'};
M_.endo_names(29) = {'RnRn'};
M_.endo_names_tex(29) = {'RnRn'};
M_.endo_names_long(29) = {'RnRn'};
M_.endo_names(30) = {'YY'};
M_.endo_names_tex(30) = {'YY'};
M_.endo_names_long(30) = {'YY'};
M_.endo_names(31) = {'CC'};
M_.endo_names_tex(31) = {'CC'};
M_.endo_names_long(31) = {'CC'};
M_.endo_names(32) = {'hh'};
M_.endo_names_tex(32) = {'hh'};
M_.endo_names_long(32) = {'hh'};
M_.endo_names(33) = {'WPWP'};
M_.endo_names_tex(33) = {'WPWP'};
M_.endo_names_long(33) = {'WPWP'};
M_.endo_names(34) = {'II'};
M_.endo_names_tex(34) = {'II'};
M_.endo_names_long(34) = {'II'};
M_.endo_names(35) = {'KK'};
M_.endo_names_tex(35) = {'KK'};
M_.endo_names_long(35) = {'KK'};
M_.endo_partitions = struct();
M_.param_names = cell(15,1);
M_.param_names_tex = cell(15,1);
M_.param_names_long = cell(15,1);
M_.param_names(1) = {'gy'};
M_.param_names_tex(1) = {'\frac{G}{Y}'};
M_.param_names_long(1) = {'gy'};
M_.param_names(2) = {'varrho'};
M_.param_names_tex(2) = {'\varrho'};
M_.param_names_long(2) = {'varrho'};
M_.param_names(3) = {'alp'};
M_.param_names_tex(3) = {'\alpha'};
M_.param_names_long(3) = {'alp'};
M_.param_names(4) = {'c'};
M_.param_names_tex(4) = {'c'};
M_.param_names_long(4) = {'c'};
M_.param_names(5) = {'zzeta'};
M_.param_names_tex(5) = {'\zeta'};
M_.param_names_long(5) = {'zzeta'};
M_.param_names(6) = {'betta'};
M_.param_names_tex(6) = {'\beta'};
M_.param_names_long(6) = {'betta'};
M_.param_names(7) = {'delta'};
M_.param_names_tex(7) = {'\delta'};
M_.param_names_long(7) = {'delta'};
M_.param_names(8) = {'sigma_c'};
M_.param_names_tex(8) = {'\sigma_c'};
M_.param_names_long(8) = {'sigma_c'};
M_.param_names(9) = {'rhoA'};
M_.param_names_tex(9) = {'\rho^{A}'};
M_.param_names_long(9) = {'rhoA'};
M_.param_names(10) = {'rhoG'};
M_.param_names_tex(10) = {'\rho^{G}'};
M_.param_names_long(10) = {'rhoG'};
M_.param_names(11) = {'Ass'};
M_.param_names_tex(11) = {'\bar{A}'};
M_.param_names_long(11) = {'Ass'};
M_.param_names(12) = {'phiX'};
M_.param_names_tex(12) = {'\phi^X'};
M_.param_names_long(12) = {'phiX'};
M_.param_names(13) = {'xi'};
M_.param_names_tex(13) = {'\xi'};
M_.param_names_long(13) = {'xi'};
M_.param_names(14) = {'alpha_r'};
M_.param_names_tex(14) = {'\alpha_r'};
M_.param_names_long(14) = {'alpha_r'};
M_.param_names(15) = {'alpha_pie'};
M_.param_names_tex(15) = {'\alpha_{\pi}'};
M_.param_names_long(15) = {'alpha_pie'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 35;
M_.param_nbr = 15;
M_.orig_endo_nbr = 35;
M_.aux_vars = [];
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.nonzero_hessian_eqs = [1 2 4 5 7 8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 25 26 27];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 35;
M_.eq_nbr = 35;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 7 0;
 0 8 0;
 1 9 0;
 0 10 0;
 0 11 0;
 0 12 0;
 0 13 0;
 0 14 0;
 2 15 0;
 3 16 0;
 0 17 0;
 0 18 0;
 4 19 0;
 5 20 0;
 0 21 0;
 0 22 0;
 0 23 42;
 0 24 43;
 0 25 44;
 0 26 0;
 0 27 0;
 0 28 45;
 0 29 0;
 0 30 46;
 0 31 0;
 6 32 0;
 0 33 47;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;]';
M_.nstatic = 23;
M_.nfwrd   = 6;
M_.npred   = 6;
M_.nboth   = 0;
M_.nsfwrd   = 6;
M_.nspred   = 6;
M_.ndynamic   = 12;
M_.dynamic_tmp_nbr = [18; 17; 4; 0; ];
M_.equations_tags = {
  1 , 'name' , 'LAMBDA' ;
  2 , 'name' , 'LAMBDAC' ;
  3 , 'name' , '3' ;
  4 , 'name' , 'XX' ;
  5 , 'name' , '5' ;
  6 , 'name' , 'Y' ;
  7 , 'name' , 'YW' ;
  8 , 'name' , '8' ;
  9 , 'name' , '9' ;
  10 , 'name' , 'X' ;
  11 , 'name' , 'K' ;
  12 , 'name' , 'Z1' ;
  13 , 'name' , '13' ;
  14 , 'name' , 'INVPIE' ;
  15 , 'name' , 'Rex' ;
  16 , 'name' , 'Z2' ;
  17 , 'name' , '17' ;
  18 , 'name' , 'G' ;
  19 , 'name' , '19' ;
  20 , 'name' , '20' ;
  21 , 'name' , 'Htilde' ;
  22 , 'name' , 'Jtilde' ;
  23 , 'name' , '23' ;
  24 , 'name' , 'MC' ;
  25 , 'name' , '25' ;
  26 , 'name' , '26' ;
  27 , 'name' , '27' ;
  28 , 'name' , 'YY' ;
  29 , 'name' , 'KK' ;
  30 , 'name' , 'II' ;
  31 , 'name' , 'CC' ;
  32 , 'name' , 'WPWP' ;
  33 , 'name' , 'hh' ;
  34 , 'name' , 'RR' ;
  35 , 'name' , 'RnRn' ;
};
M_.mapping.LAMBDA.eqidx = [1 ];
M_.mapping.LAMBDAC.eqidx = [2 3 4 5 19 20 ];
M_.mapping.Rex.eqidx = [12 15 34 ];
M_.mapping.h.eqidx = [1 2 5 7 8 18 33 ];
M_.mapping.WP.eqidx = [5 8 18 32 ];
M_.mapping.YW.eqidx = [6 7 8 16 ];
M_.mapping.Y.eqidx = [6 9 19 20 28 ];
M_.mapping.PWP.eqidx = [8 16 24 ];
M_.mapping.K.eqidx = [7 11 16 29 ];
M_.mapping.I.eqidx = [9 10 11 30 ];
M_.mapping.tax.eqidx = [18 ];
M_.mapping.C.eqidx = [1 2 5 9 31 ];
M_.mapping.A.eqidx = [7 26 ];
M_.mapping.G.eqidx = [9 18 27 ];
M_.mapping.X.eqidx = [10 11 12 13 ];
M_.mapping.Q.eqidx = [12 13 16 17 ];
M_.mapping.XX.eqidx = [3 4 ];
M_.mapping.Z1.eqidx = [12 13 ];
M_.mapping.Z2.eqidx = [16 17 ];
M_.mapping.MC.eqidx = [20 24 ];
M_.mapping.H.eqidx = [19 21 23 ];
M_.mapping.Htilde.eqidx = [19 21 ];
M_.mapping.J.eqidx = [20 22 23 ];
M_.mapping.Jtilde.eqidx = [20 22 ];
M_.mapping.PIE.eqidx = [4 14 21 22 23 25 ];
M_.mapping.Rn.eqidx = [4 15 17 25 35 ];
M_.mapping.INVPIE.eqidx = [14 15 17 ];
M_.mapping.RR.eqidx = [34 ];
M_.mapping.RnRn.eqidx = [35 ];
M_.mapping.YY.eqidx = [28 ];
M_.mapping.CC.eqidx = [31 ];
M_.mapping.hh.eqidx = [33 ];
M_.mapping.WPWP.eqidx = [32 ];
M_.mapping.II.eqidx = [30 ];
M_.mapping.KK.eqidx = [29 ];
M_.mapping.epsA.eqidx = [26 ];
M_.mapping.epsG.eqidx = [27 ];
M_.mapping.epsM.eqidx = [25 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [3 9 10 13 14 26 ];
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(35, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(15, 1);
M_.endo_trends = struct('deflator', cell(35, 1), 'log_deflator', cell(35, 1), 'growth_factor', cell(35, 1), 'log_growth_factor', cell(35, 1));
M_.NNZDerivatives = [108; 104; -1; ];
M_.static_tmp_nbr = [15; 7; 0; 0; ];
M_.params(1) = 0.2;
gy = M_.params(1);
M_.params(2) = 0.6073;
varrho = M_.params(2);
M_.params(3) = 0.70;
alp = M_.params(3);
M_.params(5) = 7.0;
zzeta = M_.params(5);
M_.params(4) = 1/M_.params(5);
c = M_.params(4);
M_.params(6) = 0.9871;
betta = M_.params(6);
M_.params(7) = 0.0250;
delta = M_.params(7);
M_.params(8) = 2.0;
sigma_c = M_.params(8);
M_.params(12) = 1.24;
phiX = M_.params(12);
M_.params(13) = 0.75;
xi = M_.params(13);
M_.params(14) = 0.7;
alpha_r = M_.params(14);
M_.params(15) = 1.5;
alpha_pie = M_.params(15);
M_.params(11) = 1;
Ass = M_.params(11);
M_.params(9) = 0.7;
rhoA = M_.params(9);
M_.params(10) = 0.7;
rhoG = M_.params(10);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.01)^2;
M_.Sigma_e(2, 2) = (0.01)^2;
M_.Sigma_e(3, 3) = (0.01)^2;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 40;
options_.periods = 0;
var_list_ = {'Q';'PIE';'RnRn';'YY';'CC';'II';'hh';'WPWP';'RR'};
[info, oo_, options_] = stoch_simul(M_, options_, oo_, var_list_);
save('NK_Course_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_Course_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_Course_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_Course_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_Course_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_Course_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_Course_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
