function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(18)=0;
    ys_(6)=0;
    ys_(19)=params(8);
    ys_(14)=1/params(1);
    ys_(17)=0.1098366249;
    ys_(13)=ys_(17);
    ys_(12)=0.1512401694;
    ys_(10)=1;
    ys_(3)=ys_(10);
    ys_(11)=0.7686025408;
    ys_(16)=ys_(3)/ys_(11);
    ys_(9)=ys_(17)*params(11);
    ys_(8)=ys_(3)*ys_(9);
    ys_(1)=ys_(17)*(1-params(11))-ys_(18);
    ys_(15)=0.3080562835;
    ys_(2)=0.2129;
    ys_(5)=0.2643516803;
    ys_(7)=ys_(17)*ys_(3)-ys_(2)*ys_(5);
    ys_(4)=(ys_(1)-ys_(2)^params(7)/params(7))^(-params(6))/ys_(3);
    % Auxiliary equations
end
