%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'model';
M_.dynare_version = '4.6.0';
oo_.dynare_version = '4.6.0';
options_.dynare_version = '4.6.0';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('model.log');
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'sA'};
M_.exo_names_tex(1) = {'{s_A}'};
M_.exo_names_long(1) = {'productivity shock'};
M_.exo_names(2) = {'sG'};
M_.exo_names_tex(2) = {'{s_A}'};
M_.exo_names_long(2) = {'government spending shock'};
M_.exo_names(3) = {'si'};
M_.exo_names_tex(3) = {'{s_A}'};
M_.exo_names_long(3) = {'interest rate shock'};
M_.exo_names(4) = {'sPF'};
M_.exo_names_tex(4) = {'{s_A}'};
M_.exo_names_long(4) = {'foreign price shock'};
M_.endo_names = cell(33,1);
M_.endo_names_tex = cell(33,1);
M_.endo_names_long = cell(33,1);
M_.endo_names(1) = {'C'};
M_.endo_names_tex(1) = {'{C}'};
M_.endo_names_long(1) = {'aggregate consumption'};
M_.endo_names(2) = {'H'};
M_.endo_names_tex(2) = {'{H}'};
M_.endo_names_long(2) = {'aggregate hours of work'};
M_.endo_names(3) = {'lambda'};
M_.endo_names_tex(3) = {'{\lambda}'};
M_.endo_names_long(3) = {'household큦 co-state variable'};
M_.endo_names(4) = {'P'};
M_.endo_names_tex(4) = {'{P}'};
M_.endo_names_long(4) = {'aggregate price index'};
M_.endo_names(5) = {'W'};
M_.endo_names_tex(5) = {'{W}'};
M_.endo_names_long(5) = {'wage rate'};
M_.endo_names(6) = {'B'};
M_.endo_names_tex(6) = {'{B}'};
M_.endo_names_long(6) = {'stock of net foreign assets'};
M_.endo_names(7) = {'y'};
M_.endo_names_tex(7) = {'{y}'};
M_.endo_names_long(7) = {'individual output'};
M_.endo_names(8) = {'Y'};
M_.endo_names_tex(8) = {'{Y}'};
M_.endo_names_long(8) = {'aggregate value-added output'};
M_.endo_names(9) = {'PI'};
M_.endo_names_tex(9) = {'{\Pi}'};
M_.endo_names_long(9) = {'aggregate profits'};
M_.endo_names(10) = {'pD'};
M_.endo_names_tex(10) = {'{p^D}'};
M_.endo_names_long(10) = {'individual domestic price'};
M_.endo_names(11) = {'xD'};
M_.endo_names_tex(11) = {'{x^D}'};
M_.endo_names_long(11) = {'proportional variation of the individual price'};
M_.endo_names(12) = {'MC'};
M_.endo_names_tex(12) = {'{MC}'};
M_.endo_names_long(12) = {'marginal cost'};
M_.endo_names(13) = {'theta'};
M_.endo_names_tex(13) = {'{\theta}'};
M_.endo_names_long(13) = {'firm큦 co-state variable'};
M_.endo_names(14) = {'mu'};
M_.endo_names_tex(14) = {'{\mu}'};
M_.endo_names_long(14) = {'individual markup'};
M_.endo_names(15) = {'e'};
M_.endo_names_tex(15) = {'{\varepisilon}'};
M_.endo_names_long(15) = {'demand shifter'};
M_.endo_names(16) = {'lambdaf'};
M_.endo_names_tex(16) = {'{\lambda^f}'};
M_.endo_names_long(16) = {'firm큦 co-state variable'};
M_.endo_names(17) = {'m'};
M_.endo_names_tex(17) = {'{m}'};
M_.endo_names_long(17) = {'fimr큦 optimal choice component'};
M_.endo_names(18) = {'chi'};
M_.endo_names_tex(18) = {'{\chi}'};
M_.endo_names_long(18) = {'firm큦 demand component'};
M_.endo_names(19) = {'D'};
M_.endo_names_tex(19) = {'{D}'};
M_.endo_names_long(19) = {'firm큦 quantity demanded'};
M_.endo_names(20) = {'CD'};
M_.endo_names_tex(20) = {'{C^D}'};
M_.endo_names_long(20) = {'consumption of domestic goods'};
M_.endo_names(21) = {'CF'};
M_.endo_names_tex(21) = {'{C^F}'};
M_.endo_names_long(21) = {'consumption of foreign goods'};
M_.endo_names(22) = {'PD'};
M_.endo_names_tex(22) = {'{P^D}'};
M_.endo_names_long(22) = {'domestic-goods price index'};
M_.endo_names(23) = {'PF'};
M_.endo_names_tex(23) = {'{P^F}'};
M_.endo_names_long(23) = {'foreign-goods price index'};
M_.endo_names(24) = {'GD'};
M_.endo_names_tex(24) = {'{G^D}'};
M_.endo_names_long(24) = {'government consumption of domestic goods'};
M_.endo_names(25) = {'GF'};
M_.endo_names_tex(25) = {'{G^F}'};
M_.endo_names_long(25) = {'government consumption of foreign goods'};
M_.endo_names(26) = {'AC'};
M_.endo_names_tex(26) = {'{AC}'};
M_.endo_names_long(26) = {'aggregate adjustment costs'};
M_.endo_names(27) = {'ACD'};
M_.endo_names_tex(27) = {'{ACD}'};
M_.endo_names_long(27) = {'adjustment costs purchased with domestic goods'};
M_.endo_names(28) = {'ACF'};
M_.endo_names_tex(28) = {'{ACF}'};
M_.endo_names_long(28) = {'adjustment costs purchased with imported goods'};
M_.endo_names(29) = {'G'};
M_.endo_names_tex(29) = {'{C^F}'};
M_.endo_names_long(29) = {'government consumption'};
M_.endo_names(30) = {'T'};
M_.endo_names_tex(30) = {'{C^F}'};
M_.endo_names_long(30) = {'lump-sum taxes'};
M_.endo_names(31) = {'A'};
M_.endo_names_tex(31) = {'{C^F}'};
M_.endo_names_long(31) = {'aggregate productivity'};
M_.endo_names(32) = {'X'};
M_.endo_names_tex(32) = {'{X}'};
M_.endo_names_long(32) = {'exports'};
M_.endo_names(33) = {'i'};
M_.endo_names_tex(33) = {'{C^F}'};
M_.endo_names_long(33) = {'nominal interest rate'};
M_.endo_partitions = struct();
M_.param_names = cell(18,1);
M_.param_names_tex = cell(18,1);
M_.param_names_long = cell(18,1);
M_.param_names(1) = {'psi'};
M_.param_names_tex(1) = {'psi'};
M_.param_names_long(1) = {'psi'};
M_.param_names(2) = {'sigma'};
M_.param_names_tex(2) = {'sigma'};
M_.param_names_long(2) = {'sigma'};
M_.param_names(3) = {'alpha'};
M_.param_names_tex(3) = {'alpha'};
M_.param_names_long(3) = {'alpha'};
M_.param_names(4) = {'phi'};
M_.param_names_tex(4) = {'phi'};
M_.param_names_long(4) = {'phi'};
M_.param_names(5) = {'eta'};
M_.param_names_tex(5) = {'eta'};
M_.param_names_long(5) = {'eta'};
M_.param_names(6) = {'gamma'};
M_.param_names_tex(6) = {'gamma'};
M_.param_names_long(6) = {'gamma'};
M_.param_names(7) = {'omega'};
M_.param_names_tex(7) = {'omega'};
M_.param_names_long(7) = {'omega'};
M_.param_names(8) = {'rho'};
M_.param_names_tex(8) = {'rho'};
M_.param_names_long(8) = {'rho'};
M_.param_names(9) = {'zetaA'};
M_.param_names_tex(9) = {'zetaA'};
M_.param_names_long(9) = {'zetaA'};
M_.param_names(10) = {'zetaG'};
M_.param_names_tex(10) = {'zetaG'};
M_.param_names_long(10) = {'zetaG'};
M_.param_names(11) = {'zetai'};
M_.param_names_tex(11) = {'zetai'};
M_.param_names_long(11) = {'zetai'};
M_.param_names(12) = {'zetaPF'};
M_.param_names_tex(12) = {'zetaPF'};
M_.param_names_long(12) = {'zetaPF'};
M_.param_names(13) = {'kappa'};
M_.param_names_tex(13) = {'kappa'};
M_.param_names_long(13) = {'kappa'};
M_.param_names(14) = {'n'};
M_.param_names_tex(14) = {'n'};
M_.param_names_long(14) = {'n'};
M_.param_names(15) = {'s'};
M_.param_names_tex(15) = {'s'};
M_.param_names_long(15) = {'s'};
M_.param_names(16) = {'varphi'};
M_.param_names_tex(16) = {'varphi'};
M_.param_names_long(16) = {'varphi'};
M_.param_names(17) = {'gshare'};
M_.param_names_tex(17) = {'gshare'};
M_.param_names_long(17) = {'gshare'};
M_.param_names(18) = {'nx'};
M_.param_names_tex(18) = {'nx'};
M_.param_names_long(18) = {'nx'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 33;
M_.param_nbr = 18;
M_.orig_endo_nbr = 33;
M_.aux_vars = [];
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.orig_eq_nbr = 33;
M_.eq_nbr = 33;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 8 0;
 0 9 0;
 0 10 41;
 0 11 0;
 0 12 0;
 1 13 0;
 0 14 42;
 0 15 0;
 0 16 0;
 2 17 43;
 0 18 0;
 0 19 0;
 0 20 44;
 0 21 0;
 3 22 0;
 0 23 45;
 0 24 46;
 0 25 47;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 4 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 5 36 0;
 0 37 0;
 6 38 0;
 0 39 0;
 7 40 0;]';
M_.nstatic = 20;
M_.nfwrd   = 6;
M_.npred   = 6;
M_.nboth   = 1;
M_.nsfwrd   = 7;
M_.nspred   = 7;
M_.ndynamic   = 13;
M_.dynamic_tmp_nbr = [23; 10; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'Household s demand for domestic goods' ;
  2 , 'name' , 'Household s demand for imported goods' ;
  3 , 'name' , 'FOC for consumption' ;
  4 , 'name' , 'FOC for labour (hours)' ;
  5 , 'name' , 'Euler equation' ;
  6 , 'name' , 'Budget constraint' ;
  7 , 'name' , 'Aggregate consumption' ;
  8 , 'name' , 'Price index' ;
  9 , 'name' , 'Balanced budget (Ricardian equivalence)' ;
  10 , 'name' , 'Exogenous process of government spending' ;
  11 , 'name' , 'Government s demand for domestic goods' ;
  12 , 'name' , 'Government s demand for domestic goods' ;
  13 , 'name' , 'Process of the nominal interest rates' ;
  14 , 'name' , 'Exogenous process foreign prices' ;
  15 , 'name' , 'Adjustment costs' ;
  16 , 'name' , 'Share of adjustment costs purchased via domestic goods' ;
  17 , 'name' , 'Share of adjustment costs purchased via imported goods' ;
  18 , 'name' , 'firm큦 demanded quantity' ;
  19 , 'name' , 'firm큦 demand component' ;
  20 , 'name' , 'Pricing equation' ;
  21 , 'name' , ' equation' ;
  22 , 'name' , 'Theta equation' ;
  23 , 'name' , 'Marginal cost' ;
  24 , 'name' , 'Individual markup' ;
  25 , 'name' , 'Law of motion for the demand shifter' ;
  26 , 'name' , 'Exogenous process of productivity' ;
  27 , 'name' , ' euqation' ;
  28 , 'name' , 'proportional price-variation' ;
  29 , 'name' , 'Aggregate domestic price level' ;
  30 , 'name' , 'Aggregate output' ;
  31 , 'name' , 'Aggregate resources' ;
  32 , 'name' , 'Aggregate profits' ;
  33 , 'name' , 'Individual output' ;
};
M_.mapping.C.eqidx = [1 2 3 4 6 7 31 ];
M_.mapping.H.eqidx = [3 4 6 30 32 ];
M_.mapping.lambda.eqidx = [3 4 5 ];
M_.mapping.P.eqidx = [1 2 3 6 8 9 11 12 13 15 16 17 20 31 32 ];
M_.mapping.W.eqidx = [4 6 23 32 ];
M_.mapping.B.eqidx = [6 13 ];
M_.mapping.y.eqidx = [20 21 23 25 33 ];
M_.mapping.Y.eqidx = [13 15 20 30 31 32 33 ];
M_.mapping.PI.eqidx = [6 32 ];
M_.mapping.pD.eqidx = [15 20 21 22 24 27 28 29 ];
M_.mapping.xD.eqidx = [20 28 ];
M_.mapping.MC.eqidx = [23 24 27 ];
M_.mapping.theta.eqidx = [22 27 ];
M_.mapping.mu.eqidx = [24 ];
M_.mapping.e.eqidx = [25 29 30 33 ];
M_.mapping.lambdaf.eqidx = [20 21 ];
M_.mapping.m.eqidx = [20 21 22 27 ];
M_.mapping.chi.eqidx = [19 22 ];
M_.mapping.D.eqidx = [18 19 ];
M_.mapping.CD.eqidx = [1 7 18 ];
M_.mapping.CF.eqidx = [2 7 31 ];
M_.mapping.PD.eqidx = [1 8 11 16 19 29 31 ];
M_.mapping.PF.eqidx = [2 8 12 14 17 31 ];
M_.mapping.GD.eqidx = [11 18 ];
M_.mapping.GF.eqidx = [12 31 ];
M_.mapping.AC.eqidx = [15 16 17 ];
M_.mapping.ACD.eqidx = [16 18 ];
M_.mapping.ACF.eqidx = [17 31 ];
M_.mapping.G.eqidx = [9 10 11 12 31 ];
M_.mapping.T.eqidx = [6 9 ];
M_.mapping.A.eqidx = [23 26 30 ];
M_.mapping.X.eqidx = [18 31 ];
M_.mapping.i.eqidx = [5 6 13 ];
M_.mapping.sA.eqidx = [26 ];
M_.mapping.sG.eqidx = [10 ];
M_.mapping.si.eqidx = [13 ];
M_.mapping.sPF.eqidx = [14 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [6 10 15 23 29 31 33 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(33, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(18, 1);
M_.endo_trends = struct('deflator', cell(33, 1), 'log_deflator', cell(33, 1), 'growth_factor', cell(33, 1), 'log_growth_factor', cell(33, 1));
M_.NNZDerivatives = [141; -1; -1; ];
M_.static_tmp_nbr = [22; 10; 0; 0; ];
M_.params(8) = 0.02177818086464089;
rho = M_.params(8);
M_.params(6) = 2;
gamma = M_.params(6);
M_.params(7) = 1.455;
omega = M_.params(7);
M_.params(7) = 1.5;
omega = M_.params(7);
M_.params(14) = 0.5;
n = M_.params(14);
M_.params(15) = 2.9;
s = M_.params(15);
M_.params(15) = 2.5;
s = M_.params(15);
M_.params(13) = 0.00742;
kappa = M_.params(13);
M_.params(10) = 0.98;
zetaG = M_.params(10);
M_.params(17) = 0.3372392;
gshare = M_.params(17);
M_.params(17) = 0.33;
gshare = M_.params(17);
M_.params(11) = 0.9;
zetai = M_.params(11);
M_.params(12) = 0.25;
zetaPF = M_.params(12);
M_.params(18) = (-0.08);
nx = M_.params(18);
M_.params(2) = M_.params(15);
sigma = M_.params(2);
M_.params(4) = 0.5;
phi = M_.params(4);
M_.params(5) = 0.125;
eta = M_.params(5);
M_.params(9) = 0.6;
zetaA = M_.params(9);
M_.params(3) = 0.3333333333333333;
alpha = M_.params(3);
M_.params(16) = 0.2;
varphi = M_.params(16);
M_.params(1) = .55;
psi = M_.params(1);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
resid;
model_diagnostics(M_,options_,oo_);
options_.ar = 1;
options_.irf = 16;
options_.nograph = true;
options_.order = 1;
var_list_ = {'C';'H';'lambda';'P';'W';'B';'y';'Y';'PI';'pD';'MC';'theta';'mu';'e';'CD';'CF';'PD';'PF';'GD';'GF';'T';'G';'A';'i';'X';'AC';'ACD';'ACF'};
[info, oo_, options_] = stoch_simul(M_, options_, oo_, var_list_);
oo_base = oo_;
M_base  = M_;
save('model_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('model_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('model_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('model_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('model_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('model_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('model_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
